// ============================================================================
// Full-course PDF export
// ----------------------------------------------------------------------------
// A single, polished, multi-page reading copy of the whole course — title page,
// snapshot, outcomes, then every module's pages, assignments, discussions, and
// quizzes in Canvas order. Uses the shared dependency-free PDF engine (pdfDoc.ts)
// with real headings, bullets, color, rules, and a page footer.
// ============================================================================

import type { CourseProject } from "../types";
import { slugify, stripHtml } from "../utils/text";
import { PdfDoc } from "./pdfDoc";

const byId = <T extends { id: string }>(items: T[], id: string): T | undefined => items.find((item) => item.id === id);

const buildDoc = (course: CourseProject): PdfDoc => {
  const doc = new PdfDoc().theme(course.theme.accent, course.theme.accentDark);
  doc.setFooter(course.title || "RocketCourse course");

  // Title page
  doc.title(course.title || "Course");
  doc.subtitle("Course reading copy - generated by RocketCourse");
  if (course.description) doc.para(course.description);
  doc.spacer(8);

  // Snapshot
  doc.keyValue("Modules", String(course.modules.length));
  doc.keyValue("Pages", String(course.pages.length));
  doc.keyValue("Assignments", String(course.assignments.length));
  doc.keyValue("Discussions", String(course.discussions.length));
  doc.keyValue("Quizzes", String(course.quizzes.length));

  if (course.outcomes.length) {
    doc.heading("Course Learning Outcomes");
    course.outcomes.forEach((outcome) => doc.bullet(`${outcome.code}: ${outcome.text} (${outcome.bloomLevel})`));
  }

  [...course.modules]
    .sort((a, b) => a.order - b.order)
    .forEach((module, moduleIndex) => {
      doc.heading(`Module ${moduleIndex + 1}: ${module.title}`, 15);
      if (module.description) doc.para(module.description);
      if (module.objectives?.length) {
        doc.subheading("Module objectives");
        module.objectives.forEach((objective) => doc.bullet(objective));
      }

      module.items.forEach((item) => {
        const page = byId(course.pages, item.refId);
        if (page) {
          doc.subheading(page.title);
          doc.html(page.bodyHtml);
          return;
        }
        const assignment = byId(course.assignments, item.refId);
        if (assignment) {
          doc.subheading(`Assignment - ${assignment.title}`);
          if (assignment.points != null) doc.note(`${assignment.points} points`);
          doc.html(assignment.descriptionHtml);
          return;
        }
        const discussion = byId(course.discussions, item.refId);
        if (discussion) {
          doc.subheading(`Discussion - ${discussion.title}`);
          doc.html(discussion.promptHtml);
          return;
        }
        const quiz = byId(course.quizzes, item.refId);
        if (quiz) {
          doc.subheading(`Quiz - ${quiz.title}`);
          if (quiz.purpose) doc.para(quiz.purpose);
          quiz.questions.forEach((question, index) => doc.bullet(`Q${index + 1}. ${stripHtml(question.stem)}`));
        }
      });
    });

  return doc;
};

/** Build the raw PDF document string for the whole course. */
export const buildCoursePdf = (course: CourseProject): string => buildDoc(course).build();

/** A downloadable PDF Blob of the whole course. */
export const generateCoursePdfBlob = (course: CourseProject): Blob => buildDoc(course).blob();

/** Suggested download file name for the course PDF. */
export const coursePdfFileName = (course: CourseProject): string => `${slugify(course.title || "course")}-course.pdf`;
