// ============================================================================
// Syllabus PDF export
// ----------------------------------------------------------------------------
// A clean, printable PDF of the course syllabus, built from the same syllabus
// page that becomes the Canvas syllabus — so the PDF and the Canvas page stay
// aligned. Renders the page's real structure (headings, lists, paragraphs).
// ============================================================================

import type { CourseProject, CoursePage } from "../types";
import { slugify } from "../utils/text";
import { PdfDoc } from "./pdfDoc";

/** The page that backs the Canvas syllabus (slug "syllabus"), if present. */
export const findSyllabusPage = (course: CourseProject): CoursePage | undefined =>
  course.pages.find((page) => page.slug === "syllabus") ??
  course.pages.find((page) => /syllabus/i.test(page.title));

export const buildSyllabusPdfBlob = (course: CourseProject): Blob => {
  const doc = new PdfDoc();
  doc.setFooter(`${course.title || "Course"} - Syllabus`);
  const syllabus = findSyllabusPage(course);

  doc.title(course.title || "Course Syllabus");
  doc.subtitle("Course Syllabus");
  if (course.description) doc.para(course.description);
  doc.spacer(6);

  if (syllabus) {
    // Render the real syllabus page structure (it already includes outcomes, schedule, policies).
    doc.html(syllabus.bodyHtml);
  } else {
    if (course.outcomes.length) {
      doc.heading("Course Learning Outcomes", 14);
      course.outcomes.forEach((outcome) => doc.bullet(`${outcome.code}: ${outcome.text}`));
    }
    doc.para(
      "No dedicated syllabus page was found in this course. Add a syllabus in the Syllabus tab to export it here."
    );
  }

  doc.spacer(10);
  doc.rule();
  doc.note(
    "This PDF mirrors the Canvas syllabus page generated by RocketCourse. Review dates, policies, grading, and " +
      "institutional requirements before publishing to students."
  );
  return doc.blob();
};

export const syllabusPdfFileName = (course: CourseProject): string => `${slugify(course.title || "course")}-syllabus.pdf`;
